In [1]:
 #Step-1  Import required modules

import numpy as np
import pandas as pd

# Sklearn library
from sklearn import preprocessing

In [2]:
# Step -2  Read data file

df1 = pd.read_csv('https://github.com/naman9034/admission-pre/raw/naman9034-patch-2/Data_for_preprocessing1.csv')
df1

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain   NaN      NaN        No
4  Germany  40.0   1000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  78.0  52000.0        No
7   France   NaN  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0      NaN       Yes

In [3]:
# Step -3 Assign input

X = df1.iloc[:, :-1].values
#This function return all columns except last as an array

In [4]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', nan, nan],
       ['Germany', 40.0, 1000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 78.0, 52000.0],
       ['France', nan, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, nan]], dtype=object)

In [5]:
# we can write above statement as column start from 0

a=df1.iloc[:, :3].values
a


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', nan, nan],
       ['Germany', 40.0, 1000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 78.0, 52000.0],
       ['France', nan, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, nan]], dtype=object)

In [6]:
#Step 4 - Manage missing values
#fill missing value mean value

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan , strategy = 'mean')

In [7]:
#Now decide actual column for treatment of missing value

imputer = imputer.fit(X[:,1:3])

In [8]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', nan, nan],
       ['Germany', 40.0, 1000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 78.0, 52000.0],
       ['France', nan, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, nan]], dtype=object)

In [9]:
#Here actual operation begins
X[:, 1:3] = imputer.transform(X[:, 1:3])
X
# Now numeric column with Nan value filled with mean


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 42.625, 55875.0],
       ['Germany', 40.0, 1000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 78.0, 52000.0],
       ['France', 42.625, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 55875.0]], dtype=object)

In [10]:
# We can use single function in place of fit and transform as fit_transform

X[:, 1:3] = imputer.fit_transform(X[:, 1:3])
X


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 42.625, 55875.0],
       ['Germany', 40.0, 1000.0],
       ['France', 35.0, 58000.0],
       ['Spain', 78.0, 52000.0],
       ['France', 42.625, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 55875.0]], dtype=object)

In [11]:
df1

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain   NaN      NaN        No
4  Germany  40.0   1000.0       Yes
5   France  35.0  58000.0       Yes
6    Spain  78.0  52000.0        No
7   France   NaN  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0      NaN       Yes

In [12]:
#Step 5 - Now treat categorical data

from sklearn.preprocessing import LabelEncoder
#use this class to convert country (text) value in numeric value
labelencoder_X = LabelEncoder()

labelencoder_X.fit(X[:,0])
X[:,0] = labelencoder_X.transform(X[:,0])
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 42.625, 55875.0],
       [1, 40.0, 1000.0],
       [0, 35.0, 58000.0],
       [2, 78.0, 52000.0],
       [0, 42.625, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 55875.0]], dtype=object)

In [13]:
# fit_transform treat categorical data in single step

X[:,0] = labelencoder_X.fit_transform(X[:,0])
X


array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 42.625, 55875.0],
       [1, 40.0, 1000.0],
       [0, 35.0, 58000.0],
       [2, 78.0, 52000.0],
       [0, 42.625, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 55875.0]], dtype=object)

In [14]:
# use onehotencoding

from numpy import asarray
from sklearn.preprocessing import OneHotEncoder
# define data
data = asarray([['red'], ['green'], ['blue']])
print(data)
# define one hot encoding

encoder = OneHotEncoder(sparse=False)
# transform data
onehot = encoder.fit_transform(data)
print(onehot)

[['red']
 ['green']
 ['blue']]
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [16]:
df1 = pd.read_csv('https://github.com/naman9034/admission-pre/raw/naman9034-patch-2/Data_for_preprocessing1.csv')
df1=pd.get_dummies(df1)
df1

Age   Salary  Country_France  Country_Germany  Country_Spain  \
0  44.0  72000.0               1                0              0   
1  27.0  48000.0               0                0              1   
2  30.0  54000.0               0                1              0   
3   NaN      NaN               0                0              1   
4  40.0   1000.0               0                1              0   
5  35.0  58000.0               1                0              0   
6  78.0  52000.0               0                0              1   
7   NaN  79000.0               1                0              0   
8  50.0  83000.0               0                1              0   
9  37.0      NaN               1                0              0   

   Purchased_No  Purchased_Yes  
0             1              0  
1             0              1  
2             1              0  
3             1              0  
4             0              1  
5             0              1  
6             1              0  
7             0              1  
8             1              0  
9             0              1

In [17]:
# Step 6- Now split data into two parts training and test

from sklearn.model_selection import train_test_split

In [18]:
# Now set value for y

y=df1.iloc[:,-1:]
y


Purchased_Yes
0              0
1              1
2              0
3              0
4              1
5              1
6              0
7              1
8              0
9              1

In [19]:
X_train, X_test, Y_train, Y_test = train_test_split(X,y, test_size=0.2)

In [20]:
X_train

array([[1, 50.0, 83000.0],
       [0, 37.0, 55875.0],
       [2, 27.0, 48000.0],
       [0, 42.625, 79000.0],
       [1, 40.0, 1000.0],
       [0, 44.0, 72000.0],
       [1, 30.0, 54000.0],
       [2, 78.0, 52000.0]], dtype=object)

In [21]:
X_test

array([[0, 35.0, 58000.0],
       [2, 42.625, 55875.0]], dtype=object)

In [22]:
Y_train

Purchased_Yes
8              0
9              1
1              1
7              1
4              1
0              0
2              0
6              0

In [23]:
Y_test

Purchased_Yes
5              1
3              0

In [24]:
from sklearn.preprocessing import StandardScaler

sc_X = StandardScaler()

X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [25]:
X_train

array([[ 0.16012815,  0.43513557,  1.13957155],
       [-1.12089708, -0.44572281,  0.01105118],
       [ 1.44115338, -1.12330618, -0.31658377],
       [-1.12089708, -0.06458216,  0.9731538 ],
       [ 0.16012815, -0.2424478 , -2.27199235],
       [-1.12089708,  0.02858555,  0.68192274],
       [ 0.16012815, -0.92003117, -0.06695714],
       [ 1.44115338,  2.332369  , -0.15016602]])

In [26]:
X_test

array([[-1.12089708, -0.58123948,  0.09946061],
       [ 1.44115338, -0.06458216,  0.01105118]])